a: resnet50
gpu: 0
train-data: /homes/oester/datasets/camelyon16/preprocessed/training/tumor
train-sampling: down
test-data: /homes/oester/datasets/camelyon16/preprocessed/testing/images
test-sampling: down
model-path: logdir/simsiam/simsiam_model-2021-10-12_14_59_50
checkpoint: checkpoint_0009.pth.tar
k: 5