a: resnet50
dist-url: tcp://localhost:10001
gpu: 0
world-size: 1 
rank: 0 
data: /home/oester/projects/ganomaly/data/breakhist_for_ganomaly
multiprocessing-distributed: true
pretrained: checkpoints/checkpoint_0099.pth.tar