a: resnet50
dist-url: tcp://localhost:10001
ngpus: 2
world-size: 1 
rank: 0 
fix-pred-lr: true
batch-size: 512
train-data: /home/oester/projects/simsiam/data/breakhist_for_simsiam/train
multiprocessing-distributed: true