a: resnet50
gpu: 0
test-data: /homes/oester/datasets/camelyon16/preprocessed/testing/images
model-path: logdir/simsiam/simsiam_model-2021-10-12_14_59_50
checkpoint: checkpoint_0009.pth.tar
test-sampling: down